### PR TITLE
CB-11913 - Re-fix appveyor.yml to use specific node versions

### PR DESCRIPTION
**Pull request by shazron**
### Platforms affected

All

### What does this PR do?

Fix appveyor.yml node versions, they were incorrect previously

### What testing has been done on this change?

The test will be on Appveyor (automated with this PR)

### Checklist
- [X] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [X] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [X] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by shazron** [comment]
Now that I've got appveyor node versions "working", it reflects the node 6 failures on Travis. Now to get node 6 working (npm link shenanigans).

**Comment by shazron** [comment]
Might be related: https://github.com/npm/npm/issues/9633

**Comment by shazron** [comment]
Nah its https://github.com/npm/npm/issues/10343

**Comment by stevengill** [comment]
hows it going on this?

**Comment by shazron** [comment]
@stevengill unfortunately https://github.com/npm/npm/issues/9633 strikes its head (see AppVeyor failure). Usually running `npm install` again fixes it, but once the first `npm install` fails it just fails the build

**Comment by shazron** [comment]
@stevengill since `yarn` works flawlessly on `node 6` the alternative is, put all the `install` commands in a script and use `yarn` when we detect `node 6`. Kinda like my script here: https://github.com/npm/npm/issues/10343#issuecomment-253358042

**Comment by shazron** [comment]
Final fix that worked: downgrade to npm@2

**Pull request closed without merging**
