### PR TITLE
CB-10748 Use cordova-common.CordovaLogger in CLI

### PR DESCRIPTION
**Pull request by daserge**
[Jira issue](https://issues.apache.org/jira/browse/CB-10748)

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
LGTM

**Comment by nikhilkh** [comment]
What about the Travis CI failures?

**Comment by daserge** [comment]
@nikhilkh, I'm investigating it.

**Comment by daserge** [comment]
@nikhilkh, the issue was in the missing `\n` - help.spec was trying to parse an incorrect line.
BTW we could improve the help so that command aliases are taken into account:
`cordova plugins --help` output would be same as `cordova plugin --help` (created [CB-10786](https://issues.apache.org/jira/browse/CB-10786)).

**Comment by vladimir-kotikov** [comment]
:ship:

**Comment by nikhilkh** [comment]
Are there still some test failures? @daserge Could you also add the travis badge for cordova-cli

**Comment by daserge** [comment]
@nikhilkh 

> Are there still some test failures?
No, tests should be green now.

> Could you also add the travis badge for cordova-cli? 
Sure, will do.

**Pull request merged**
