### PR TITLE
CLI Refactor

### PR DESCRIPTION
**Pull request by omefire**
- Moves init, update checking & args parsing into a separate module
- Cleans up telemetry handling code by generalizing it
- Increases readability

### CODE REVIEW

**Comment by brutalcrozt** [comment]
update?

**Comment by stevengill** [comment]
Hey @omefire, should i review this?

**Comment by omefire** [comment]
@stevengill sure, plz review it.

**Comment by brodybits** [comment]
Status?

**Comment by purplecabbage** [comment]
This now has conflicts, and even more when considered with other prs.  Should I look to reimplement this cleanly?

**Comment by purplecabbage** [comment]
Ima close this soon.

**Pull request closed without merging**
