### PR TITLE
Fix issues in cordova@8.1.0

### LINKED ISSUE #337: cordova@8.1.0 breaks when prompting for telemetry opt-in
Hi, 

After installing `npm install -g cordova` no cordova commands work at all
Every command asks if you can track, answering yes or no make no difference
Ticks around a while then reports the following error
Tried reinstall, uninstall / reinstall
No luck

Cant check version because that too results in error - but I just ran normal install command

```
/Users/rgb/.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/insight/lib/index.js:156
		prompt.close();
		       ^

TypeError: prompt.close is not a function
    at Insight.<anonymous> (/Users/rgb/.nvm/versions/node/v8.9.4/lib/node_modules/cordova/node_modules/insight/lib/index.js:156:10)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

Also tried globally installing an npm module called `prompt` incase that was the issue - no luck

### PR DESCRIPTION
**Pull request by raphinesse**
Fixes #337 and #339

### CODE REVIEW

**Comment by raphinesse** [comment]
`npm-shrinkwrap.json` is not "no longer needed". It will make sure that everyone that installs the release will get the exact same dependency versions that we tested the release with. From now on and for all time.

**Comment by raphinesse** [comment]
Anyhow, if the shrinkwrap-or-not issue should prevent us from doing a quick hotfix release then I'm fine either way. Please feel free to merge or adapt this the way you see fit @brodybits. My availability will be limited today.

**Comment by brodybits** [comment]
@raphinesse does that mean you want me to make the new patch release?

**Comment by brodybits** [comment]
And does your comment mean we should consider introducing `npm-shrinkwrap.json` in master? If so, I would rather discuss in an issue or dev email.

**Comment by raphinesse** [comment]
@brodybits

> And does your comment mean we should consider introducing npm-shrinkwrap.json in master? If so, I would rather discuss in an issue or dev email.

No, I mean including it in releases. I *have* already elaborated my stance on this in great detail on the mailing list. I know you asked for clarification there, but I didn't know how to express myself more clearly then. I might give it another try when I find some time for it.

> does that mean you want me to make the new patch release?

You have the tools setup and a good experience with preparing releases. I have neither of these things and I'm on a tight schedule right now. So it would be great if you could do the patch release :bowing_man:

**Pull request merged**
