### PR TITLE
CB-9523 Show out of date message for older cordova CLI

### PR DESCRIPTION
**Pull request by daserge**
Used [update-notifier](https://github.com/yeoman/update-notifier) module

### CODE REVIEW

**Comment by stevengill** [comment]
Good idea. Things to think about though.

1) what if the user says no to updating. The message should not show up everytime they use cordova. Some global variable to remember we have shown the message and not to show it again. Maybe the variable gets reset when they upgrade. 
2) what if some other packages are depending on cordova-cli (i know they should use lib). We should have a flag to not show updates.

**Comment by nikhilkh** [comment]
+1 to a flag to disable updatecheck - `disableupdatecheck` - Looks like update-notifier has a number of ways to disable update check:

https://www.npmjs.com/package/update-notifier#user-settings

We should test these and perhaps document them in cordova-cli docs.

**Comment by daserge** [comment]
@stevengill, @nikhilkh, 
Verified (works OK) and documented the ways to disable updates check, please take a look.

**Comment by nikhilkh** [comment]
Thanks! LGTM

**Comment by nikhilkh** [comment]
@daserge Would be great to merge this.

**Pull request closed without merging**
