### PR TITLE
Handle output error strings

### PR DESCRIPTION
**Pull request by piotr-cz**
### Platforms affected
all

Host OS: at least Windows

### Motivation and Context

Properly output error strings

### Description

When command rejects with a string, it's special characters like newlines and tabs are not formatted,

Example:
```
cordova platform update cordova-ios --save

Using cordova-fetch for cordova-ios
Updating ios project...
CordovaError: Promise rejected with non-error: 'An in-place platform update is not supported. \nThe `platforms` folder is always treated as a build artifact.\nTo update your platform, you have to remove, then add your ios platform again.\nMake sure you save your plugins beforehand using `cordova plugin save`, and save a copy of the platform first if you had manual changes in it.\n\tcordova plugin save\n\tcordova platform rm ios\n\tcordova platform add ios\n'
    at cli.catch.err (xxx\node_modules\cordova\bin\cordova:29:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```
After:
```
cordova platform update cordova-ios --save
Using cordova-fetch for cordova-ios
Updating ios project...
CordovaError: Promise rejected with non-error: An in-place platform update is not supported.
The `platforms` folder is always treated as a build artifact.
To update your platform, you have to remove, then add your ios platform again.
Make sure you save your plugins beforehand using `cordova plugin save`, and save a copy of the platform first if you had manual changes in it.
        cordova plugin save
        cordova platform rm ios
        cordova platform add ios

    at cli.catch.err (xxx\node_modules\cordova\bin\cordova:33:15)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

### Checklist

- [ ] I've run the tests to see all new and existing tests pass
- [ ] I added automated test coverage as appropriate for this change
- [ ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [ ] I've updated the documentation if necessary

### CODE REVIEW

**Comment by raphinesse** [comment]
In case you know where that string is thrown, it would be great if you could create a PR to properly throw an Error instead.

Throwing objects other than Errors should be avoided since they provide no stack traces.

**Comment by piotr-cz** [comment]
@raphinesse:
It's coming from [cordova-ios > create comand](https://github.com/apache/cordova-ios/blob/5.0.1/bin/lib/create.js#L243-L255).
Most promises in that library are rejected with strings instead of CordovaError

Also in [cordova-android: bin/templates/cordova/lib/run.js](https://github.com/apache/cordova-android/blob/8.0.0/bin/templates/cordova/lib/run.js#L99)

**Comment by raphinesse** [comment]
@piotr-cz Thanks for the information!

**Comment by piotr-cz** [comment]
Sure, I just don't feel comfortable enough yet in cordova internals to create PRs for these packages.

**Pull request merged**
