### PR TITLE
CB-12008 : made autosave the default for platform and plugin add/rm and included jasmine tests

### PR DESCRIPTION
**Pull request by audreyso**
CB-12008 : made autosave the default for platform and plugin add/rm and included jasmine tests

### What does this PR do?
Makes save the default setting for platform and plugin add/remove. Use --nosave if you do not want to add or remove.

### What testing has been done on this change?
New jasmine tests added (platform and plugin add and remove with/without --nosave).

### Checklist
- [X] [Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database
- [X] Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.
- [X] Added automated test coverage as appropriate for this change.

### CODE REVIEW

**Comment by audreyso** [comment]
The proposal has been updated.
https://github.com/audreyso/cordova-discuss/commit/1daa86c0dfa4760f5130f4e587ba787a72fe15f9

Autosave will only be used in the cli right now (not cordova-lib).... you will still need to use the --save flag if using cordova-lib directly.

**Comment by brodybits** [comment]
I hope to see this integrated soon. I have seen way too many new users keeping old plugins in git instead of just adding them to config.xml.

**Comment by stevengill** [comment]
Here is the discussion for the proposal: https://github.com/cordova/cordova-discuss/pull/61

**Comment by stevengill** [comment]
@audreyso can you add some docs about --nosave, remove --save & discuss autosave to various files in https://github.com/apache/cordova-cli/tree/master/doc. cordova.txt, platform.txt, plugin.txt are the obvious ones. Not sure if other docs in there have references to save.

We will also need to add updates to cordova-docs repo as well before releasing cordova-7

**Comment by stevengill** [comment]
Your cordova-cli PRs are ready to rebase now :)

**Comment by audreyso** [comment]
Thanks! @stevengill  ...Rebased cli PR's! Let me know if I need to make any additional changes!

**Pull request closed without merging**
